---
- name: INSTALANDO PACODE DE DESENVOLVIMENTO DEVELOPMENT TOOLS
  dnf: 
    name: "@development-tools"
    state: present
    validate_certs: true


- name: INSTALANDO DEPENDENCIAS VIRTUALBOX
  dnf: 
    name: "{{ item }}"
    state: present
    validate_certs: true
  loop:
    - kernel-headers
    - kernel-devel
    - dkms
    - elfutils-libelf-devel
    - qt5-qtx11extras


- name: MOVENDO ARQUIVO DE SCRIPT DO REPO RPM
  copy:
    src: files/virtualbox-fedora-37.sh
    dest: /home/willian/Downloads
    owner: "{{ MY_USER_VAR }}"
    mode: 0755


- name: EXECUTANDO SCRIPT DO REPO RPM
  shell:
    cmd: bash /home/willian/Downloads/virtualbox-fedora-37.sh


- name: BUSCANDO REPOSITORIO
  shell:
    cmd: sudo dnf search virtualbox


- name: INSTALANDO VIRTUALBOX
  dnf: 
    name: VirtualBox-7.0
    state: present
    validate_certs: true


# - name: CRIANDO GRUPO VBXUSERS
#   group:
#     name: vboxusers
#     state: present


# - name: ADICIONANDO VBXUSERS PARA USUARIO DO SISTEMA
#   user:
#     name: "{{ MY_USER_VAR }}"
#     groups: vboxusers
#     append: yes


- name: CRIANDO GRUPO VBXUSERS
  shell:
    cmd: sudo usermod -a -G vboxusers $USER


- name: REMOVENDO SCRIPT VIRTUALBOX-FEDORA-37
  file:
    path: /home/willian/Downloads/virtualbox-fedora-37.sh
    state: absent